image: hhy5861/golang-ci:1.0.3

stages:
  - build
  - deploy

variables:
  DEV_DOMAIN: "http://${CI_PROJECT_NAME}.dev.fashionipo.com"
  DEV_SSH_IP: "10.10.10.126"
  DEV_SSH_PORT: "22"

  BETA_DOMAIN: "http://${CI_PROJECT_NAME}.beta.fashionipo.com"
  BETA_SSH_IP: "172.16.1.235"
  BETA_SSH_PORT: "22"

  GO_PATH_DOMAIN: "gopkg.fashionipo.com/fashionipo"

before_script:
  - mkdir -p ~/.ssh
  - ssh-keyscan -H -t ecdsa -p $DEV_SSH_PORT $DEV_SSH_IP >> ~/.ssh/known_hosts
  - ssh-keyscan -H -t ecdsa -p $BETA_SSH_PORT $BETA_SSH_IP >> ~/.ssh/known_hosts
  - echo "$ID_RSA" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
  - mkdir -p "${GOPATH}/src/${GO_PATH_DOMAIN}/${CI_PROJECT_NAME}" && cp -r ./* ${GOPATH}/src/${GO_PATH_DOMAIN}/${CI_PROJECT_NAME}
  - cd ${GOPATH}/src/${GO_PATH_DOMAIN}/${CI_PROJECT_NAME}

build-dev:
  stage: build
  script:
    - make
    - rsync -avzH -e "ssh -p $DEV_SSH_PORT" --delete ./${CI_PROJECT_NAME}-linux-amd64 $DEV_SSH_IP:/data/golang/${CI_PROJECT_NAME}/
  tags:
    - develop
  only:
    - Alpha

build-beta:
  stage: build
  script:
    - make
    - rsync -avzH -e "ssh -p $BETA_SSH_PORT" --delete ./${CI_PROJECT_NAME}-linux-amd64 $BETA_SSH_IP:/data/golang/${CI_PROJECT_NAME}/
  tags:
    - beta
  only:
    - Beta

# 开发环境
develop:
  stage: deploy
  script:
    - rsync -avzH -e "ssh -p $DEV_SSH_PORT" --delete ./config/alpha/config.yaml $DEV_SSH_IP:/data/golang/${CI_PROJECT_NAME}/config/config.yaml
    - ssh $DEV_SSH_IP -p $DEV_SSH_PORT "if [ -e "/data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}" ]; then rm -f /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}; fi && mv /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}-linux-amd64 /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME} && supervisorctl restart ${CI_PROJECT_NAME}"
  environment:
    name: Alpha
    url: $DEV_DOMAIN
  only:
    - Alpha
  except:
    - GA
  tags:
    - develop

# 测试环境
beta:
  stage: deploy
  script:
    - rsync -avzH -e "ssh -p $BETA_SSH_PORT" --delete ./config/beta/config.yaml $BETA_SSH_IP:/data/golang/${CI_PROJECT_NAME}/config/config.yaml
    - ssh $BETA_SSH_IP -p $BETA_SSH_PORT "if [ -e "/data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}" ]; then rm -f /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}; fi && mv /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME}-linux-amd64 /data/golang/${CI_PROJECT_NAME}/${CI_PROJECT_NAME} && supervisorctl restart ${CI_PROJECT_NAME}"
  environment:
    name: Beta
    url: $BETA_DOMAIN
  only:
    - Beta
  except:
    - GA
  tags:
    - beta